### ISSUE TITLE
AddMember is internal

### ISSUE THREAD

**Issue by erzki** [shahriarhossain/MailChimp.Api.Net#5]
Method AddMember is internal in class MailChimpList. Is this by design?
How do I then add members?

**Comment by shahriarhossain** [comment]
**Good catch**. That was by _mistake_!

I will make it public and push an update to nuget as well.

**Comment by shahriarhossain** [comment]
I have just pushed a quick update : nuget 1.2.0.1. 

Hope this will solve the issue.

**Comment by erzki** [comment]
Thanks

One more question. Is the Thread.Sleep neccessary in the batch operations?

Erik

ons 2 mars 2016 kl 17:13 skrev Shahriar Hossain notifications@github.com:

**Comment by shahriarhossain** [comment]
@erzki : Thread.Sleep() is necessary if you want to do further work with that batch. What I mean is that, after doing batch request if you intend to do some work with that batch(lets say, you want to check the result of that batch) then you have to use the Thread.Sleep, this is good practice. Otherwise , you might not get the appropriate result. Its not documented in mailchimp api, its something that I have figured out while playing with their api.
